version: '2'
services:
    catpowerserver-app:
        image: catpowerserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://catpowerserver-mysql:3306/catpowerserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    catpowerserver-mysql:
        extends:
            file: mysql.yml
            service: catpowerserver-mysql
